config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users
  resources :posts do
    resources :comments
  end


  root 'posts#index'
  # resources :comments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :content, presence: true, length: { in: 2..50 }
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { in: 6..50 }
  validates :content, presence: true
  has_many :comments
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
  mount_uploader :avatar, AvatarUploader
  validates :name, presence: true, length: { in: 10..40 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    @post = Post.find(params[:post_id])
    @comment =  @post.comments.create comment_params
    redirect_to post_path @post
  end

  def destroy
    @post = Post.find(params[:id])
    @comment = Comment.find(params[:post_id])
    @comment.destroy
    redirect_to post_path @post
  end

  private

  def comment_params
    params.required(:comment).permit(:post_id, :content).merge(user_id: current_user.id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @posts = Post.order('created_at DESC').page(params[:page]).per(4)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else render 'posts/new'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def edit
    @post = Post.find(params[:id])

  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else render 'posts/edit'
    end
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.order('created_at DESC').page(params[:page]).per(4)
  end

  private

  def post_params
    params.require(:post).permit(:title, :content).merge(user_id: current_user.id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:update]
  def show
    @user = current_user
    @posts = current_user.posts.order('created_at DESC').page(params[:page]).per(4)
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.update user_params
    redirect_to user_path @user
  end

  private

  def user_params
    params.require(:user).permit(:name, :bio, :company, :avatar)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tumbler</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'general' %>
    <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
  </head>

  <body>
  <div class="row">

    <div class="col-md-2"></div>
    <div class="col-md-8">

<!--      MAIN APP-->
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="<%= posts_path %>">Tumbler</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse">
          <% if current_user %>
          <div class="navbar-nav">
            <a class="nav-item nav-link active" href="<%= posts_path %>" > New feeds </a>
            <a class="nav-item nav-link" href="<%= user_path current_user.id %>">Profile</a>
          </div>
            <% end %>
        </div>


        <div class="collapse navbar-collapse">
          <div class="navbar-nav">
            <% if user_signed_in? %>
              <p class="nav-item nav-link"><%= current_user.email %></p>
              <%= link_to "Create new post", new_post_path, class: "nav-item nav-link" %>
              <%= link_to "Logout", destroy_user_session_path, class: "nav-item nav-link", method: :delete, data: { confirm: "Are you sure?" } %>
            <% else %>
              <%= link_to "Login" , new_user_session_path, class: "nav-item nav-link" %>
              <%= link_to "Sign up", new_user_registration_path, class: "nav-item nav-link" %>
            <% end %>
          </div>
        </div>
      </nav>
      <div class="container-fluid">

        <% unless notice.nil? %>
          <p class="notice alert alert-success"><%= notice %></p>
        <% end %>

        <% unless alert.nil? %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>


        <%= yield %>

      </div>
    </div>
    <div class="col-md-2"></div>

  </div>

  </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.hidden_field :user_id %>
  <%= f.button :submit, class: "btn-primary" %>
  <%= link_to "Back", posts_path, class: "btn btn-default" %>
<% end %>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= render 'posts/form' %>

app/views/posts/index.html.erb
<h1><b>All Posts</b></h1>

<!--<p><%#= link_to "Create new post", new_post_path %></p>-->

<% @posts.each do |post| %>

  <h3><%= link_to post.title, post_path(post.id) %></h3>
  <p><%= post.user.email %> | <%= time_ago_in_words post.created_at %> ago</p>
  <p><%= truncate(post.content , length: 50) %></p>
  <hr>
<% end %>

<%= paginate @posts, theme: 'twitter-bootstrap-4' %>

app/views/posts/new.html.erb
<h1>Create new post</h1>

<%= render 'posts/form' %>

app/views/posts/show.html.erb
<h1><b><%= @post.title %></b></h1>
<h5>Author: <%= @post.user.email %></h5>
<i>Created <%= time_ago_in_words(@post.created_at) %> ago</i>

<% if current_user.eql? @post.user %>

  <%= link_to "Back", posts_path %> |
  <%= link_to "Edit", edit_post_path %> |
  <%= link_to "Delete", post_path, method: :delete, data: {confirm: "Are you sure about that?"}  %>
<% end %>

<hr>
<br>


<p><%= @post.content %></p>
<hr>


<h3>Add a comments</h3>

<%= simple_form_for Comment.new, url: post_comments_path(@post) do |f| %>
  <%= f.input :content %>
  <%= f.hidden_field :post_id, value: @post.id %>
  <%= f.button :submit %>
<% end %>

<p><%= @comments.count %> comments</p>
<% @comments.each do |c| %>
  <p><b><%= c.user.email %></b> | <%= time_ago_in_words c.created_at %> ago</p>

  <p><%= c.content %></p>

  <% if current_user.eql? c.user %>
    <%= link_to "Delete", post_comment_path(c.id), method: :delete,  data: {confirm: "Are you sure about that?"} %>
  <% end %>
<% end %>

<%= paginate @comments, theme: 'twitter-bootstrap-4' %>

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.error_notification %>
  <%= f.input :name %>
  <%= f.input :avatar, as: :file %>
  <%= f.input :bio %>
  <%= f.input :company %>
  <%= f.button :submit, class: "btn-primary" %>
  <%= link_to "Back", user_path, class: "btn btn-default" %>
<% end %>

app/views/users/edit.html.erb
<h1>Update profile</h1>

<%= render 'users/form' %>

app/views/users/show.html.erb
<h1>Profile</h1>
<div class="row">
  <div class="col-md-4">
    <% if @user.avatar.to_s.empty? %>
      <img src="https://i.pinimg.com/236x/94/d0/31/94d0319c6ad9424b614d99ccd5c29b67.jpg" alt="<%= @user.email %>" class="img-responsive rounded" width="250" height="250">
    <% else %>
      <img src="<%= @user.avatar.to_s %>" alt="<%= @user.email %>" class="img-responsive rounded" width="250" height="250">
    <% end %>
    <p>Name: <%= @user.name.nil? ? "Unknown" : @user.name %></p>
    <p><%= @user.email %></p>
    <p>Bio: <%= @user.bio.nil? ? "Unknown" : @user.bio %></p>
    <p>Company: <%= @user.company.nil? ?  "Unknown" : @user.company %></p>
    <p>Joined <%= @user.created_at.strftime("%F") %></p>

    <%= link_to "Update your profile", edit_user_path, class: "btn btn-primary" %>
  </div>

  <div class="col-md-8">
    <% if @posts.count.zero? %>
      <p>You dont have any posts. Why not create one?</p>
    <% end %>
    <%= link_to "Create new post", new_post_path, class: "btn btn-primary" %>
    <hr>
    <% @posts.each do |post| %>
      <h2><%= link_to post.title, post_path(post.id) %></h2>
      <p><%= truncate post.content, length: 100 %></p>
    <% end %>
    <%= paginate @posts, theme: 'twitter-bootstrap-4' %>
  </div>
</div>